name: easyr1
channels:
  - defaults
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.10
  - pytorch=2.1
  - pytorch-cuda=12.1  # 按你机器驱动版本选择，例如12.1/11.8
  - numpy>=1.24
  - tqdm
  - pip>=23.0
  - pip:
      - transformers>=4.35.0
      - datasets>=2.12.0
      - trl>=0.6.0
      - peft>=0.4.0
      - accelerate>=0.19.0
      - tokenizers>=0.13.0
      - sentencepiece
      - safetensors
      - evaluate
      - scipy
      - regex
      - wandb
      - tensorboard